spring:
  datasource:
    # 数据库名，从配置 database.name 中获取
    url: jdbc:mysql://192.168.81.131:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.81.131
    port: 6379
    password:

#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志